### ISSUE TITLE
PR: Add support for `eslint-plugin-flowtype-errors`

### ISSUE THREAD

**Issue by amilajack** [exponentjs/ex-navigation#174]
This plugin allows flow to be run as an eslint plugin 🎉 Would a PR for this be welcome?

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

**Comment by satya164** [comment]
Why won't you use the regular flow plugin for the editor though, which will provide both error checking and autocomplete?

**Comment by amilajack** [comment]
which one?

**Comment by satya164** [comment]
@amilajack For Atom there are several, Nuclide works great. I had also tried ide-flow which was working fine.

For sublime, there is https://packagecontrol.io/packages/FlowIDE

**Comment by amilajack** [comment]
@satya164 most people already have eslint integration in their IDE/text editor and don't want to change their workflow and environment just to use flow.

**Comment by satya164** [comment]
@amilajack That's not true. Nobody has to change their workflow, eslint still works as previous. They just have to use an additional plugin for flow which provides all the flow features like error checking, autocomplete, jump to reference etc. It's the same for things like babel or typescript, elm or anything for that matter.

If you integrate this plugin to eslint, then it forces people to change their workflow. Now I have to disable error checking for the flow plugin, since I don't want to give up on the autocompletion feature the plugin provides. Also I have to use this plugin in all projects since I also want to get errors and I've error checking disabled in my flow plugin. This also means that both plugins might conflict with each other since they have to manage running a flow server.

In addition, it's no longer immediately clear what are flow errors and what are eslint errors. Sure, it shows the plugin name, but it's not as obvious. This is not good, since most of the time Flow errors mean there are actually errors in my code, while ESLint is mostly just suggesting things might be wrong.

**Comment by amilajack** [comment]
closing this then
