### ISSUE TITLE
weird shadow under navbar

### ISSUE THREAD

**Issue by ivpusic** [exponentjs/ex-navigation#186]
<img width="304" alt="screen shot 2016-10-20 at 1 01 51 am" src="https://cloud.githubusercontent.com/assets/450140/19540604/e7b426b8-9660-11e6-8522-a50af44a4209.png">

As you can see there is a shadow under navbar. I tried quickly to pinpoint from where it comes, and it seems that with removing https://github.com/exponentjs/ex-navigation/blob/3788c8723ddaf5f457691ca9a7972fd3e0b8044e/src/ExNavigationBar.js#L364 shadow disappears. Didn't go further what else this change may affect.

**Comment by joypatel04** [comment]
@ivpusic If you are on android that's the normal behavior of navigationBar on Android that it render  with `elevation: 4` and it looks like you can't remove it because that's the default style but you may override the style with help of this [overrideStyle](https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationBar.js#L228) to override containerStyle.

**Comment by chirag04** [comment]
you can disable the elevation i think using
```
navigationBar: {
   elevation: 0,
}
```

**Comment by joypatel04** [comment]
@chirag04 yep you are correct [elevation?: number,](https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationTypeDefinition.js.flow#L44)

**Comment by ivpusic** [comment]
tnx guys
