### ISSUE TITLE
Why vendoring NavigationExperimental?

### ISSUE THREAD

**Issue by ptomasroos** [exponentjs/ex-navigation#4]
Is this because RN Experimental is continously improving? 

Can't we just freeze the version that was expected to work instead?

Whats the reason for doing this?

**Comment by skevy** [comment]
There's two reasons:

1) NavigationExperiemental is changing constantly. I would like to make sure this lib continues to work while NavExperimental continues to stabilize.
2) Internally at Exponent we have to support 0.27, and won't upgrade again until 0.29 (or possibly 0.30). At the same time, I want to make sure we're supporting people externally. Vendoring allows this.

Note, this is a temporary measure. I won't vendor NavEx forever, and as soon as @hedgerwang and @ericvicenti say "NavEx is stable!", I will get rid of the vendored dep. Also, you can expect that I will periodically update the vendored NavEx so that any ex-nav users get to take advantage of any underlying improvements made on NavEx that would affect this lib.
